### ISSUE TITLE
Create LMS admin panel and a todo app that interfaces with said panel

### ISSUE THREAD

**Issue by BrooksPatton** [brooks-builds/backlog#15]
My vision is to have a LMS back end which I can see who has registered for which tutorial projects and where they are in each tutorial.

The client side that learners will see will be a tutorial in itself, requiring the learner to build it first.

Obviously I'll have one available for download just in case as well.

- [ ] Create 2 or more course/tutorial ideas and how they would look
- [ ] Design the admin panel to show where learners are in the process of the courses
- [ ] Design the learner side of the LMS, how the learners will get new courses, track their progress, and report success
- [ ] Create projects for each of the pieces that are needed for the admin panel
- [ ] Create tutorial for building the front-end of the LMS for the learner-side
